version: "3"
services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./grafana/config:/etc/grafana
      - ./grafana/data:/var/lib/grafana
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    stdin_open: true
    tty: true
    volumes:
      - ./prometheus:/etc/prometheus
      - ./metrics:/prometheus
    ports:
      - 9090:9090
