grafana: # Visualize metrics from Prometheus
    image: grafana/grafana-enterprise
    container_name: grafana
    hostname: grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/etc/grafana # Configuration file
      - grafana_data:/var/lib/grafana
    restart: always

  prometheus: # OSS for server/system monitoring
    image: prom/prometheus
    container_name: prometheus
    hostname: prometheus
    volumes:
      - ./prometheus:/etc/prometheus # Configuration file
      - metrics_data:/prometheus
    ports:
      - 9090:9090
    restart: always
    networks:
      - prom